# -*- coding: utf-8 -*-
"""classification_logisticregression

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZiOUJP-oHzt6f-kYv5TvBfOPWP-UCrM8
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt

data = pd.read_csv('/content/Europe Sales Records.csv')

X = data[['Units Sold', 'Unit Cost']]
y = data['Total Cost']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)


model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Ortalama Kare Hata (Mean Squared Error):", mse)
print("R^2 Skoru:", r2)

plt.scatter(y_test, y_pred)
plt.xlabel('Gerçek Değerler')
plt.ylabel('Tahminler')
plt.title('Gerçek vs. Tahmin Edilen Değerler')
plt.show()