# -*- coding: utf-8 -*-
"""regression

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RRDu8hGTUv7rsNdJRDkLBLWyAIJmpm6C
"""

import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt


np.random.seed(0)
X = 2 * np.random.rand(100, 1)
y = 3 + 4 * X + np.random.randn(100, 1)

model = LinearRegression()
model.fit(X, y)

X_new = np.array([[0], [2]])
y_pred = model.predict(X_new)


plt.scatter(X, y)
plt.plot(X_new, y_pred, "r-")
plt.xlabel("X")
plt.ylabel("y")
plt.title("Doğrusal Regresyon Örneği")
plt.show()

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

data = pd.read_csv('/content/Europe Sales Records.csv')

X = data[['Unit Price']]
y = data['Total Profit']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)


plt.scatter(X_test, y_test, color='black')
plt.plot(X_test, y_pred, color='blue', linewidth=3)
plt.xlabel('Bağımsız Değişken')
plt.ylabel('Bağımlı Değişken')
plt.title('Doğrusal Regresyon')
plt.show()